name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - New Tool Request
        - Helm Chart Enhancement
        - Documentation
        - Build/CI Process
        - Offline/Air-gapped Support
        - Security
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples for the feature request
      placeholder: Add any other context...

  - type: dropdown
    id: contribution
    attributes:
      label: Willing to Contribute?
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I'd like to implement this"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "No, but I can provide more details if needed"

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues/discussions to ensure this hasn't been requested
          required: true
